# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200, null=True)),
                ('index', models.CharField(max_length=1000, null=True)),
                ('ipath', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
